cargo-features = ["strip"]

[package]
name = "rstationhub"
description = "Unofficial game launcher for UnityStation"
version = "0.1.0"
edition = "2018"

[features]
default = ["rustls", "geolocation"]

rustls = ["reqwest/rustls-tls"]

native-tls = ["reqwest/native-tls"]

# cannot be disablet now
geolocation = []

[dependencies]
serde_json = "1"
crossterm = "0.21"
parking_lot = "0.11"
better-panic = "0.2.0"

[dependencies.tui]
version = "0.16.0"
features = ["crossterm"]
default-features = false

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.reqwest]
version = "0.11.4"
default-features = false
features = ["blocking", "json"]

[dependencies.log]
version = "0.4"
features = ["release_max_level_info"]

[dependencies.simple-logging]
version = "2.0.2"

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = 'abort'
